name: mjobs
description: this project will help some developer to find jobs easily..
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http:
  flutter_html:
  url_launcher:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
        

flutter_icons:
#  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/images/job_search.png"
  image_path_ios: "assets/images/job_search.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: false # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "assets/images/job_search.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/images/job_search.png" # only available for Android 8.0 devices and above

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/job_search.png
    - assets/images/Octocat.jpg
    - assets/images/so-icon.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Eroded
       fonts:
         - asset: assets/fonts/Modern Serif Eroded.ttf
         - asset: assets/fonts/Modern Serif Eroded.ttf
           style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


